### ISSUE TITLE
msg and grops

### ISSUE THREAD

**Issue by BrMohammed** [baraegh/ft_transcendence#3]
tasks of to day
## Todo
- [x] api for create msg
- [x] api for create groups
- [x] api for show all msgs
- [x] api for fetch grops  with user 
- [x] api for fetch Personel chat with user 
- [x] api for fetch all channels with user
