### ISSUE TITLE
setting of group

### ISSUE THREAD

**Issue by BrMohammed** [baraegh/ft_transcendence#4]
##TODO for owner
- [x] mute member group for owner
- [x] remove member from group
- [x] clear chat
- [x] delete group
- [x] add admin
- [x] invite user to group
- [x] edit on the group
- [x] api for check the name of group id unique
- [x] api for show the owner and users and admins with id and image and name
