### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by BrMohammed** [baraegh/ft_transcendence#7]
##TODO
- [x] edite profile
- [x] edit setting in chat
- [x] add attribute to match history : the game is end
- [x] create match
- [x] edit on match
- [x] match history 
- [x] end game: add win and los to user
- [x] profile : block, pending
- [x] leaderbourd
- [x] ranking in chat
